# --- The Clear BSD License ---
# Copyright Semtech Corporation 2024. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted (subject to the limitations in the disclaimer
# below) provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Semtech corporation nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY
# THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
# NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL SEMTECH CORPORATION BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

######################################
# target
######################################
TOP_DIR = ../../../..

APP = ranging_demo
APP_TRACE ?= yes

PROJECTS_COMMON_MAKEFILE = $(TOP_DIR)/lr11xx/common/apps_common.mk

######################################
# building variables
######################################
# debug build?
DEBUG ?= 1
# optimization
OPT ?= -O0

#######################################
# paths
#######################################

# Build path
BUILD_DIR = ./build

######################################
# source
######################################

# C sources

C_SOURCES += \
../main_$(APP).c   \
../ranging_hopping_frequency/app_ranging_hopping.c \
../ranging_hopping_frequency/app_ranging_result_output.c \
../ranging_hopping_frequency/app_ranging_lcd_display.c \
../ranging_hopping_frequency/app_software_timer.c \
../ranging_hopping_frequency/app_pathloss.c \

C_INCLUDES +=  \
-I../ranging_hopping_frequency/ \
-I../


# Initialise empty C_DEFS
C_DEFS += \
-DPERF_TEST_ENABLED \

#######################################
# include
#######################################

include $(PROJECTS_COMMON_MAKEFILE)

#######################################
# build the application
#######################################

.PHONY: all target

all: target

target: $(BUILD_DIR)/$(APP).elf $(BUILD_DIR)/$(APP).bin

.DEFAULT_GOAL:= target

## For the main application
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))

# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c $(MAKEFILE_LIST) | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s $(MAKEFILE_LIST) | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(APP).elf: $(OBJECTS) Makefile | $(BUILD_DIR)
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@
	
$(BUILD_DIR):
	mkdir $@

print-%  : ; @echo $* = $($*)

#######################################
# clean up
#######################################
clean:
	rm -fR $(BUILD_DIR)

#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# Shell colors
BOLD_RED := '\033[1;31m'
BOLD_CYAN := '\033[1;36m'
BOLD_GREEN := '\033[1;32m'
BOLD_PURPLE := '\033[1;35m'
BOLD_YELLOW:= '\033[1;33m'
YELLOW:= '\033[0;33m'
IPURPLE:= '\033[0;95m'
BIPURPLE:= '\033[1;95m'

NC := '\033[0m' # no color
ECHO = @echo -e $(LIGHT_CYAN)
ECHO_OK = @echo -e $(LIGHT_GREEN)
ECHO_CMD = /bin/echo

define echo_help
	@$(ECHO_CMD) -e $(IPURPLE)'| '$(1)$(NC)
endef

define echo_help_b
	@$(ECHO_CMD) -e $(BIPURPLE)'  '$(1)$(NC)
endef

help:
	$(call echo_help_b, "----------------------------- Compilation ----------------------------------")
	$(call echo_help, " * make RADIO_SHIELD=<TARGET>  : build this app on a given EVK target board:(default is LR1110MB1DIS)")
	$(call echo_help, "")
	$(call echo_help_b, " * RADIO_SHIELD    PCB         Frequency matching    Characteristics")
	$(call echo_help, " * LR1110MB1DIS    E516V02B    868/915 MHz           GNSS with LNA for Passive GNSS Antenna")
	$(call echo_help, " * LR1110MB1DJS    E592V01B    868/915 MHz           GNSS without LNA")
	$(call echo_help, " * LR1110MB1GIS    E516V02B    490 MHz               GNSS with LNA for Passive GNSS Antenna")
	$(call echo_help, " * LR1110MB1GJS    E592V01B    490 MHz               GNSS without LNA")
	$(call echo_help, "")
	$(call echo_help, " * LR1120MB1DIS    E655V01A    868/915 MHz           GNSS with LNA for Passive GNSS Antenna")
	$(call echo_help, " * LR1120MB1DJS    E656V01A    868/915 MHz           GNSS without LNA")
	$(call echo_help, " * LR1120MB1GIS    E655V01A    490 MHz               GNSS with LNA for Passive GNSS Antenna")
	$(call echo_help, " * LR1120MB1GJS    E656V01A    490 MHz               GNSS without LNA")
	$(call echo_help_b, "-------------------------------- Clean -------------------------------------")
	$(call echo_help, " * make clean                  : clean all")

# *** EOF ***
